version: "3.9"
services:
  clamav-mirror:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    volumes:
      - 'clamav_database:/clamav'

volumes:
  clamav_database:
