version: "3.9"
services:
  clamav-mirror:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    volumes:
      - 'clamav_database:/clamav'
    restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

volumes:
  clamav_database:
